### PR TITLE
Add impersonate capability

### PR DESCRIPTION
**Pull request by DrakkenSaer**
connects to https://github.com/keycloak/keycloak-admin-client/issues/67

### CODE REVIEW

**Comment by stianst** [comment]
The impersonate feature is really only something that is supposed to work from the KC admin console and not a general use API.

**Comment by DrakkenSaer** [comment]
Is there any other way to administratively get a user's session?

**Comment by webintoit** [comment]
You can add your custom auth flow execution, like: 
```javascript
AuthenticationManager = Java.type("org.keycloak.services.managers.AuthenticationManager");
KeycloakModelUtils = Java.type("org.keycloak.models.utils.KeycloakModelUtils");

function authenticate(context) {

    var params = httpRequest.getUri().getQueryParameters();
    var username = "";
    if(params.get("username") !== null){
        username = params.get("username")[0];
    }
    var user = KeycloakModelUtils.findUserByNameOrEmail(context.getSession(), context.getRealm(), username);
    if(user !== null){
        context.getSession().setAttribute(AuthenticationManager.SSO_AUTH, "true");
        context.setUser(user);
        context.success();
        return;
    }
    
    context.attempted();
}
```

**Comment by DrakkenSaer** [comment]
Sorry for the delay, I just came back to the problem. I cannot make any changes to our Keycloak client, we are moving our users over to another authentication service and I am writing a proxy between them. I am only able to make API calls between the two services & cannot setup a custom auth flow. Is there an API based approach I can take to do the same thing?

**Comment by webintoit** [comment]
POST /admin/realms/{realm}/authentication/executions

http://www.keycloak.org/docs-api/2.5/rest-api/index.html#_add_new_authentication_execution

**Comment by webintoit** [comment]
Please look for ActionToken  docs,  it can help you.

**Comment by stianst** [comment]
This library is no longer being maintained, please use https://github.com/keycloak/keycloak-nodejs-admin-client instead

**Pull request closed without merging**
